#print("Hello World!",end='')
print("Hello Again",end='')
print("I like type this")
print("This is fun")
print('Yay!\nPrinting.')
print("i'd much rather you 'not'.")
print('i "said" do not touch this.')
